#!/usr/bin/env bash
set -euo pipefail

export DUUI_READABILITY_ANNOTATOR_NAME=duui-readability
export DUUI_READABILITY_ANNOTATOR_VERSION=0.0.1

#export DUUI_READABILITY_LOG_LEVEL=DEBUG
export DUUI_READABILITY_LOG_LEVEL=INFO

export DOCKER_REGISTRY="docker.texttechnologylab.org/"

docker build \
  --build-arg DUUI_READABILITY_ANNOTATOR_NAME \
  --build-arg DUUI_READABILITY_ANNOTATOR_VERSION \
  --build-arg DUUI_READABILITY_LOG_LEVEL \
  -t ${DOCKER_REGISTRY}${DUUI_READABILITY_ANNOTATOR_NAME}:${DUUI_READABILITY_ANNOTATOR_VERSION} \
  -f "src/main/docker/Dockerfile" \
  .

docker tag \
  ${DOCKER_REGISTRY}${DUUI_READABILITY_ANNOTATOR_NAME}:${DUUI_READABILITY_ANNOTATOR_VERSION} \
  ${DOCKER_REGISTRY}${DUUI_READABILITY_ANNOTATOR_NAME}:latest
