FROM ubuntu:20.04
RUN apt-get update && apt-get install -y wget unzip

COPY config.toml /app/
COPY Rocket.toml /app/
COPY communication_layer.lua /app/
COPY resources/ /app/resources/

ENV VERSION="1.3.0"
RUN wget "https://github.com/texttechnologylab/gazetteer-rs/releases/download/v${VERSION}/gazetteer-rs.${VERSION}-gui.zip"
RUN unzip "gazetteer-rs.${VERSION}-gui.zip" -x resources/* config.toml Rocket.toml -d /app/
RUN chmod +x /app/gazetteer

WORKDIR /app

EXPOSE 80

ENV ROCKET_ADRESS="0.0.0.0"
ENV ROCKET_PORT=80

CMD ./gazetteer