#!/usr/bin/env bash
set -euo pipefail

export TEXTIMAGER_DUUI_VADER_SENTIMENT_ANNOTATOR_NAME=duui-vader-sentiment
export TEXTIMAGER_DUUI_VADER_SENTIMENT_ANNOTATOR_VERSION=0.1.0

#export TEXTIMAGER_DUUI_VADER_SENTIMENT_LOG_LEVEL=DEBUG
export TEXTIMAGER_DUUI_VADER_SENTIMENT_LOG_LEVEL=INFO

export DOCKER_REGISTRY="docker.texttechnologylab.org/"

docker build \
  --build-arg TEXTIMAGER_DUUI_VADER_SENTIMENT_ANNOTATOR_NAME \
  --build-arg TEXTIMAGER_DUUI_VADER_SENTIMENT_ANNOTATOR_VERSION \
  --build-arg TEXTIMAGER_DUUI_VADER_SENTIMENT_LOG_LEVEL \
  -t ${DOCKER_REGISTRY}${TEXTIMAGER_DUUI_VADER_SENTIMENT_ANNOTATOR_NAME}:${TEXTIMAGER_DUUI_VADER_SENTIMENT_ANNOTATOR_VERSION} \
  -f "src/main/docker/Dockerfile" \
  .

docker tag \
  ${DOCKER_REGISTRY}${TEXTIMAGER_DUUI_VADER_SENTIMENT_ANNOTATOR_NAME}:${TEXTIMAGER_DUUI_VADER_SENTIMENT_ANNOTATOR_VERSION} \
  ${DOCKER_REGISTRY}${TEXTIMAGER_DUUI_VADER_SENTIMENT_ANNOTATOR_NAME}:latest
