#!/usr/bin/env bash
set -euo pipefail

export DUUI_OLLAMA_LANGCHAIN_ANNOTATOR_NAME=duui-ollama-langchain
export DUUI_OLLAMA_LANGCHAIN_ANNOTATOR_VERSION=0.0.4

#export DUUI_OLLAMA_LANGCHAIN_LOG_LEVEL=DEBUG
export DUUI_OLLAMA_LANGCHAIN_LOG_LEVEL=INFO

export DOCKER_REGISTRY="docker.texttechnologylab.org/"

docker build \
  --build-arg DUUI_OLLAMA_LANGCHAIN_ANNOTATOR_NAME \
  --build-arg DUUI_OLLAMA_LANGCHAIN_ANNOTATOR_VERSION \
  --build-arg DUUI_OLLAMA_LANGCHAIN_LOG_LEVEL \
  -t ${DOCKER_REGISTRY}${DUUI_OLLAMA_LANGCHAIN_ANNOTATOR_NAME}:${DUUI_OLLAMA_LANGCHAIN_ANNOTATOR_VERSION} \
  -f "src/main/docker/Dockerfile" \
  .

docker tag \
  ${DOCKER_REGISTRY}${DUUI_OLLAMA_LANGCHAIN_ANNOTATOR_NAME}:${DUUI_OLLAMA_LANGCHAIN_ANNOTATOR_VERSION} \
  ${DOCKER_REGISTRY}${DUUI_OLLAMA_LANGCHAIN_ANNOTATOR_NAME}:latest
