#!/usr/bin/env bash
set -euo pipefail

export TEXT_TO_IMAGE_ANNOTATOR_CUDA=
#export EMOTION_ANNOTATOR_CUDA="-cuda"

export TEXT_TO_IMAGE_ANNOTATOR_NAME=duui-text-to-image
export TEXT_TO_IMAGE_ANNOTATOR_VERSION=0.2.0
export TEXT_TO_IMAGE_LOG_LEVEL=DEBUG
export TEXT_TO_IMAGE_MODEL_CACHE_SIZE=3
export DOCKER_REGISTRY="docker.texttechnologylab.org/"
export TEXT_TO_IMAGE_HUGGING_FACE_TOKEN="unset"


docker build \
  --build-arg TEXT_TO_IMAGE_ANNOTATOR_NAME \
  --build-arg TEXT_TO_IMAGE_ANNOTATOR_VERSION \
  --build-arg TEXT_TO_IMAGE_LOG_LEVEL \
  -t ${DOCKER_REGISTRY}${TEXT_TO_IMAGE_ANNOTATOR_NAME}:${TEXT_TO_IMAGE_ANNOTATOR_VERSION}${TEXT_TO_IMAGE_ANNOTATOR_CUDA} \
  -f src/main/docker/Dockerfile${TEXT_TO_IMAGE_ANNOTATOR_CUDA} \
  .

docker tag \
  ${DOCKER_REGISTRY}${TEXT_TO_IMAGE_ANNOTATOR_NAME}:${TEXT_TO_IMAGE_ANNOTATOR_VERSION}${TEXT_TO_IMAGE_ANNOTATOR_CUDA} \
  ${DOCKER_REGISTRY}${TEXT_TO_IMAGE_ANNOTATOR_NAME}:latest${TEXT_TO_IMAGE_ANNOTATOR_CUDA}

