#!/usr/bin/env bash
set -euo pipefail

export EMOTION_ANNOTATOR_CUDA=
#export EMOTION_ANNOTATOR_CUDA="-cuda"

export EMOTION_ANNOTATOR_NAME=duui-transformers-emotion
export EMOTION_ANNOTATOR_VERSION=0.2.0
export EMOTION_LOG_LEVEL=DEBUG
export EMOTION_MODEL_CACHE_SIZE=3
export DOCKER_REGISTRY="docker.texttechnologylab.org/"


docker build \
  --build-arg EMOTION_ANNOTATOR_NAME \
  --build-arg EMOTION_ANNOTATOR_VERSION \
  --build-arg EMOTION_LOG_LEVEL \
  -t ${DOCKER_REGISTRY}${EMOTION_ANNOTATOR_NAME}:${EMOTION_ANNOTATOR_VERSION}${EMOTION_ANNOTATOR_CUDA} \
  -f src/main/docker/Dockerfile${EMOTION_ANNOTATOR_CUDA} \
  .

docker tag \
  ${DOCKER_REGISTRY}${EMOTION_ANNOTATOR_NAME}:${EMOTION_ANNOTATOR_VERSION}${EMOTION_ANNOTATOR_CUDA} \
  ${DOCKER_REGISTRY}${EMOTION_ANNOTATOR_NAME}:latest${EMOTION_ANNOTATOR_CUDA}
