#!/usr/bin/env bash
set -euo pipefail

export DUUI_CANARY_ANNOTATOR_NAME=duui-canary
export DUUI_CANARY_ANNOTATOR_VERSION=0.0.1

export DUUI_CANARY_VARIANT=
#export DUUI_CANARY_VARIANT=-cuda

export DUUI_CANARY_LOG_LEVEL=DEBUG
#export DUUI_CANARY_LOG_LEVEL=INFO

export DOCKER_REGISTRY="docker.texttechnologylab.org/"

docker build \
  --build-arg DUUI_CANARY_ANNOTATOR_NAME \
  --build-arg DUUI_CANARY_ANNOTATOR_VERSION \
  --build-arg DUUI_CANARY_LOG_LEVEL \
  -t ${DOCKER_REGISTRY}${DUUI_CANARY_ANNOTATOR_NAME}:${DUUI_CANARY_ANNOTATOR_VERSION}${DUUI_CANARY_VARIANT} \
  -f "src/main/docker/Dockerfile${DUUI_CANARY_VARIANT}" \
  --progress=plain \
  .

docker tag \
  ${DOCKER_REGISTRY}${DUUI_CANARY_ANNOTATOR_NAME}:${DUUI_CANARY_ANNOTATOR_VERSION}${DUUI_CANARY_VARIANT} \
  ${DOCKER_REGISTRY}${DUUI_CANARY_ANNOTATOR_NAME}:latest${DUUI_CANARY_VARIANT}
