#!/usr/bin/env bash
set -euo pipefail

export SUMMARY_ANNOTATOR_CUDA=
#export SUMMARY_ANNOTATOR_CUDA="-cuda"

export SUMMARY_ANNOTATOR_NAME=duui-transformers-summary
export SUMMARY_ANNOTATOR_VERSION=0.2.0
export SUMMARY_LOG_LEVEL=DEBUG
export SUMMARY_MODEL_CACHE_SIZE=3
export DOCKER_REGISTRY="docker.texttechnologylab.org/"

docker build \
  --build-arg SUMMARY_ANNOTATOR_NAME \
  --build-arg SUMMARY_ANNOTATOR_VERSION \
  --build-arg SUMMARY_LOG_LEVEL \
  -t ${DOCKER_REGISTRY}${SUMMARY_ANNOTATOR_NAME}:${SUMMARY_ANNOTATOR_VERSION}${SUMMARY_ANNOTATOR_CUDA} \
  -f src/main/docker/Dockerfile${SUMMARY_ANNOTATOR_CUDA} \
  .

docker tag \
  ${DOCKER_REGISTRY}${SUMMARY_ANNOTATOR_NAME}:${SUMMARY_ANNOTATOR_VERSION}${SUMMARY_ANNOTATOR_CUDA} \
  ${DOCKER_REGISTRY}${SUMMARY_ANNOTATOR_NAME}:latest${SUMMARY_ANNOTATOR_CUDA}