#!/usr/bin/env bash
set -euo pipefail

export DUUI_WHISPERX_ANNOTATOR_NAME=duui-whisperx
export DUUI_WHISPERX_ANNOTATOR_VERSION=3.0.0

#export DUUI_WHISPERX_VARIANT=
export DUUI_WHISPERX_VARIANT=-cuda

#export DUUI_WHISPERX_LOG_LEVEL=DEBUG
export DUUI_WHISPERX_LOG_LEVEL=INFO

export DOCKER_REGISTRY="docker.texttechnologylab.org/"

docker build \
  --build-arg DUUI_WHISPERX_ANNOTATOR_NAME \
  --build-arg DUUI_WHISPERX_ANNOTATOR_VERSION \
  --build-arg DUUI_WHISPERX_LOG_LEVEL \
  -t ${DOCKER_REGISTRY}${DUUI_WHISPERX_ANNOTATOR_NAME}:${DUUI_WHISPERX_ANNOTATOR_VERSION}${DUUI_WHISPERX_VARIANT} \
  -f "src/main/docker/Dockerfile${DUUI_WHISPERX_VARIANT}" \
  --progress=plain \
  .

docker tag \
  ${DOCKER_REGISTRY}${DUUI_WHISPERX_ANNOTATOR_NAME}:${DUUI_WHISPERX_ANNOTATOR_VERSION}${DUUI_WHISPERX_VARIANT} \
  ${DOCKER_REGISTRY}${DUUI_WHISPERX_ANNOTATOR_NAME}:latest${DUUI_WHISPERX_VARIANT}
