#!/usr/bin/env bash
set -euo pipefail

# Name and version of the tool
# These are defined here to keep the versions in Python and Docker synchronized
export TTLAB_DUUI_TRANSFORMERS_SENTIMENT_EXAMPLE_ANNOTATOR_NAME=duui-transformers-sentiment-example
export TTLAB_DUUI_TRANSFORMERS_SENTIMENT_EXAMPLE_ANNOTATOR_VERSION=1.0.0

# docker registry to use
export TTLAB_DUUI_DOCKER_REGISTRY="docker.texttechnologylab.org/"

# Build the Docker image
docker build \
  --build-arg TTLAB_DUUI_TRANSFORMERS_SENTIMENT_EXAMPLE_ANNOTATOR_NAME \
  --build-arg TTLAB_DUUI_TRANSFORMERS_SENTIMENT_EXAMPLE_ANNOTATOR_VERSION \
  -t ${TTLAB_DUUI_DOCKER_REGISTRY}${TTLAB_DUUI_TRANSFORMERS_SENTIMENT_EXAMPLE_ANNOTATOR_NAME}:${TTLAB_DUUI_TRANSFORMERS_SENTIMENT_EXAMPLE_ANNOTATOR_VERSION} \
  -f "src/main/docker/Dockerfile" \
  .

# Automatically tag the newest image as "latest"
docker tag \
  ${TTLAB_DUUI_DOCKER_REGISTRY}${TTLAB_DUUI_TRANSFORMERS_SENTIMENT_EXAMPLE_ANNOTATOR_NAME}:${TTLAB_DUUI_TRANSFORMERS_SENTIMENT_EXAMPLE_ANNOTATOR_VERSION} \
  ${TTLAB_DUUI_DOCKER_REGISTRY}${TTLAB_DUUI_TRANSFORMERS_SENTIMENT_EXAMPLE_ANNOTATOR_NAME}:latest
