export FACT_ANNOTATOR_NAME=duui-factchecking
export FACT_ANNOTATOR_VERSION=0.1.0
export FACT_LOG_LEVEL=INFO
eport FACT_MODEL_CACHE_SIZE=3
export  FACT_MODEL_NAME=unieval
export FACT_MODEL_VERSION="d33e7b6cfebe97b2bafe435adbd818230d5a416a"
#export  FACT_MODEL_NAME=nubia
#export FACT_MODEL_VERSION="ba6569605671e88217a14b2b218ce6974be73775"
export DOCKER_REGISTRY="docker.texttechnologylab.org/"
export DUUI_CUDA=
#export DUUI_CUDA="-cuda"

docker build \
  --build-arg FACT_ANNOTATOR_NAME \
  --build-arg FACT_ANNOTATOR_VERSION \
  --build-arg FACT_LOG_LEVEL \
  --build-arg FACT_MODEL_CACHE_SIZE \
  --build-arg FACT_MODEL_NAME \
  --build-arg FACT_MODEL_VERSION \
  -t ${DOCKER_REGISTRY}${FACT_ANNOTATOR_NAME}"-"${FACT_MODEL_NAME}:${FACT_ANNOTATOR_VERSION}${DUUI_CUDA} \
  -f src/main/docker/Dockerfile${DUUI_CUDA} \
  .

docker tag \
  ${DOCKER_REGISTRY}${FACT_ANNOTATOR_NAME}"-"${FACT_MODEL_NAME}:${FACT_ANNOTATOR_VERSION}${DUUI_CUDA} \
  ${DOCKER_REGISTRY}${FACT_ANNOTATOR_NAME}"-"${FACT_MODEL_NAME}:latest${DUUI_CUDA}