FROM nvidia/cuda:11.0.3-base-ubuntu20.04

RUN apt update && \
    DEBIAN_FRONTEND=noninteractive \
    apt install --no-install-recommends -y build-essential software-properties-common && \
    add-apt-repository -y ppa:deadsnakes/ppa && \
    apt install --no-install-recommends -y python3.8 python3-pip python3-setuptools python3-distutils && \
    apt clean && rm -rf /var/lib/apt/lists/*

RUN ln -s /usr/bin/python3 /usr/bin/python
RUN python -m pip install --upgrade pip

WORKDIR /usr/src/app

EXPOSE 9714


# meta data
ARG FACT_ANNOTATOR_NAME="duui-Factchecking:app"
ENV FACT_ANNOTATOR_NAME=$FACT_ANNOTATOR_NAME
ARG FACT_ANNOTATOR_VERSION="unset"
ENV FACT_ANNOTATOR_VERSION=$FACT_ANNOTATOR_VERSION

# log level
ARG FACT_LOG_LEVEL="DEBUG"
ENV FACT_LOG_LEVEL=$FACT_LOG_LEVEL

# config
ARG FACT_MODEL_CACHE_SIZE=3
ENV FACT_MODEL_CACHE_SIZE=$FACT_MODEL_CACHE_SIZE

# Model Info
ARG FACT_MODEL_NAME=""
ENV FACT_MODEL_NAME=$FACT_MODEL_NAME
ARG FACT_MODEL_VERSION=0.1
ENV FACT_MODEL_VERSION=$FACT_MODEL_VERSION

# service script
COPY ./src/main/python/TypeSystemFactChecking.xml ./TypeSystemFactChecking.xml
COPY ./src/main/python/scorer.py ./scorer.py
COPY ./src/main/python/evaluator.py ./evaluator.py
COPY ./src/main/python/utils.py ./utils.py
COPY ./src/main/python/factchecker.py ./factchecker.py
COPY ./src/main/python/duui_fact.lua ./duui_fact.lua
COPY ./src/main/python/duui_fact.py ./duui_fact.py
COPY ./reqiurements.txt ./reqiurements.txt

RUN pip install torch==2.2.0 torchvision==0.17.0 torchaudio==2.2.0 --index-url https://download.pytorch.org/whl/cu118
RUN pip install -r reqiurements.txt
RUN python -m nltk.downloader punkt
RUN python -c "from evaluator import get_evaluator; get_evaluator('fact', device='cpu')"
#RUN python -c "from nubia_score import Nubia; nubia = Nubia()"


ENTRYPOINT ["uvicorn", "duui_fact:app", "--host", "0.0.0.0", "--port" ,"9714"]
CMD ["--workers", "1"]

