#!/usr/bin/env bash
set -euo pipefail

# Transformer-based
#export DUUI_SENTENCIZER_SPACY_VARIANT=trf
# Rule-based
export DUUI_SENTENCIZER_SPACY_VARIANT=ruler
# Dependency parser
#export DUUI_SENTENCIZER_SPACY_VARIANT=parser-sm
#export DUUI_SENTENCIZER_SPACY_VARIANT=parser-md
#export DUUI_SENTENCIZER_SPACY_VARIANT=parser-lg
# Statistical segmenter
#export DUUI_SENTENCIZER_SPACY_VARIANT=senter-sm
#export DUUI_SENTENCIZER_SPACY_VARIANT=senter-md
#export DUUI_SENTENCIZER_SPACY_VARIANT=senter-lg

export DUUI_SENTENCIZER_SPACY_ANNOTATOR_NAME=duui-sentencizer-spacy
export DUUI_SENTENCIZER_SPACY_ANNOTATOR_VERSION=0.0.1

#export DUUI_SENTENCIZER_SPACY_LOG_LEVEL=DEBUG
export DUUI_SENTENCIZER_SPACY_LOG_LEVEL=INFO

export DUUI_SENTENCIZER_SPACY_MODEL_CACHE_SIZE=2

export DOCKER_REGISTRY="docker.texttechnologylab.org/"

docker build \
  --build-arg DUUI_SENTENCIZER_SPACY_ANNOTATOR_NAME \
  --build-arg DUUI_SENTENCIZER_SPACY_ANNOTATOR_VERSION \
  --build-arg DUUI_SENTENCIZER_SPACY_LOG_LEVEL \
  --build-arg DUUI_SENTENCIZER_SPACY_MODEL_CACHE_SIZE \
  --build-arg DUUI_SENTENCIZER_SPACY_VARIANT \
  -t ${DOCKER_REGISTRY}${DUUI_SENTENCIZER_SPACY_ANNOTATOR_NAME}-${DUUI_SENTENCIZER_SPACY_VARIANT}:${DUUI_SENTENCIZER_SPACY_ANNOTATOR_VERSION} \
  -f "src/main/docker/Dockerfile" \
  .

docker tag \
  ${DOCKER_REGISTRY}${DUUI_SENTENCIZER_SPACY_ANNOTATOR_NAME}-${DUUI_SENTENCIZER_SPACY_VARIANT}:${DUUI_SENTENCIZER_SPACY_ANNOTATOR_VERSION} \
  ${DOCKER_REGISTRY}${DUUI_SENTENCIZER_SPACY_ANNOTATOR_NAME}-${DUUI_SENTENCIZER_SPACY_VARIANT}:latest
