FROM nvidia/cuda:11.0.3-base-ubuntu20.04

RUN apt update && \
    DEBIAN_FRONTEND=noninteractive \
    apt install --no-install-recommends -y build-essential software-properties-common && \
    add-apt-repository -y ppa:deadsnakes/ppa && \
    apt install --no-install-recommends -y python3.10 python3-pip python3-setuptools python3-distutils && \
    apt clean && rm -rf /var/lib/apt/lists/*

RUN ln -s /usr/bin/python3 /usr/bin/python
RUN python -m pip install --upgrade pip

WORKDIR /usr/src/app

EXPOSE 9714

# dependencies
RUN pip install setuptools wheel

COPY ./requirements.txt ./requirements.txt
RUN pip install -r requirements.txt

#RUN python -c "from transformers import pipeline; pipeline('text-classification', model='kornosk/bert-election2020-twitter-stance-trump')"
#RUN python -c "from transformers import pipeline; pipeline('zero-shot-classification', model='mlburnham/deberta-v3-base-polistance-affect-v1.0')"

# copy scripts
COPY ./src/main/python/duui_stance.lua ./duui_stance.lua
COPY ./src/main/python/StanceDetection.py ./StanceDetection.py
COPY ./src/main/python/TypeSystemStance.xml ./TypeSystemStance.xml
COPY /src/main/python/duui_stance.py ./duui_stance.py

# log level
ARG LOG_LEVEL="DEBUG"
ENV LOG_LEVEL=$LOG_LEVEL

# config
ARG MODEL_CACHE_SIZE=1
ENV MODEL_CACHE_SIZE=$MODEL_CACHE_SIZE
ARG MODEL_NAME=""
ENV MODEL_NAME=$MODEL_NAME
ARG MODEL_VERSION=""
ENV MODEL_VERSION=$MODEL_VERSION
ARG MODEL_URL=""
ENV MODEL_URL=$MODEL_URL
ARG MODEL_LANG=""
ENV MODEL_LANG=$MODEL_LANG

# meta data
ARG ANNOTATOR_NAME="duui-argument"
ENV ANNOTATOR_NAME=$ANNOTATOR_NAME
ARG ANNOTATOR_VERSION="unset"
ENV ANNOTATOR_VERSION=$ANNOTATOR_VERSION
ARG CHATGPT_KEY=""
ENV CHATGPT_KEY=$CHATGPT_KEY

ENTRYPOINT ["uvicorn", "duui_stance:app", "--host", "0.0.0.0", "--port" ,"9714"]
CMD ["--workers", "1"]