FROM nvidia/cuda:11.0.3-base-ubuntu20.04
RUN apt update && DEBIAN_FRONTEND=noninteractive \
    apt install --no-install-recommends -y build-essential software-properties-common && \
    add-apt-repository -y ppa:deadsnakes/ppa && \
    apt install --no-install-recommends -y python3.8 python3-pip python3-setuptools python3-distutils && \
    apt clean && rm -rf /var/lib/apt/lists/*
RUN ln -s /usr/bin/python3 /usr/bin/python
RUN python -m pip install --upgrade pip
WORKDIR /usr/src/app

EXPOSE 9714

# dependencies

RUN pip install symspellpy fastapi uvicorn[standard] dkpro-cassis
RUN pip install setuptools wheel
RUN pip install spacy
RUN pip install hanta
RUN pip install diaparser


# languages/models
RUN python -m spacy download "de_core_news_lg"
RUN python -c "from diaparser.parsers import Parser; Parser.load('de_hdt.dbmdz-bert-base')"
RUN python -c "from HanTa import HanoverTagger as ht; ht.HanoverTagger('morphmodel_ger.pgz')"

RUN pip install func_timeout
# meta data
ARG TEXTIMAGER_BFSRL_ANNOTATOR_NAME="textimager_duui_bfsrl_$TEXTIMAGER_DIAPARSER_BATCH_SIZE"
ENV TEXTIMAGER_BFSRL_ANNOTATOR_NAME=$TEXTIMAGER_BFSRL_ANNOTATOR_NAME
ARG TEXTIMAGER_BFSRL_ANNOTATOR_VERSION="unset"
ENV TEXTIMAGER_BFSRL_ANNOTATOR_VERSION=$TEXTIMAGER_BFSRL_ANNOTATOR_VERSION

# log level
ARG TEXTIMAGER_BFSRL_LOG_LEVEL="DEBUG"
ENV TEXTIMAGER_BFSRL_LOG_LEVEL=$TEXTIMAGER_BFSRL_LOG_LEVEL

# config
ARG TEXTIMAGER_BFSRL_PARSER_MODEL_NAME="de_hdt.dbmdz-bert-base"
ENV TEXTIMAGER_BFSRL_PARSER_MODEL_NAME=$TEXTIMAGER_BFSRL_MODEL_NAME

ARG TEXTIMAGER_SPACY_MODEL_CACHE_SIZE=3
ENV TEXTIMAGER_SPACY_MODEL_CACHE_SIZE=$TEXTIMAGER_SPACY_MODEL_CACHE_SIZE

ARG TEXTIMAGER_DIAPARSER_BATCH_SIZE=8192
ENV TEXTIMAGER_DIAPARSER_BATCH_SIZE=$TEXTIMAGER_DIAPARSER_BATCH_SIZE
# service script
COPY ./src/main/python/TypeSystemBFSRL.xml ./TypeSystemBFSRL.xml
COPY ./src/main/python/xcomp-object.txt ./xcomp-object.txt
COPY ./src/main/python/xcomp-subject.txt ./xcomp-subject.txt
COPY ./src/main/python/textimager_duui_bfsrl.lua ./textimager_duui_bfsrl.lua
COPY ./src/main/python/textimager_duui_bfsrl.py ./textimager_duui_bfsrl.py
COPY ./src/main/python/bfsrl.py ./bfsrl.py
#patch diaparser error
#https://github.com/Unipisa/diaparser/issues/9
COPY ./src/main/python/transform.py /usr/local/lib/python3.8/dist-packages/diaparser/utils/

ENTRYPOINT ["uvicorn", "textimager_duui_bfsrl:app", "--host", "0.0.0.0", "--port" ,"9714", "--use-colors"]
CMD ["--workers", "1"]
