export TEXTIMAGER_SRL_PARSER_BATCH_SIZE=$1
export TEXTIMAGER_SRL_ANNOTATOR_NAME=srl_cuda_$TEXTIMAGER_SRL_PARSER_BATCH_SIZE
export TEXTIMAGER_SRL_ANNOTATOR_VERSION=0.0.1
export TEXTIMAGER_SRL_LOG_LEVEL=INFO

docker build \
  --build-arg TEXTIMAGER_SRL_ANNOTATOR_NAME \
  --build-arg TEXTIMAGER_SRL_ANNOTATOR_VERSION \
  --build-arg TEXTIMAGER_SRL_LOG_LEVEL \
  --build-arg TEXTIMAGER_SRL_PARSER_BATCH_SIZE \
  -t ${TEXTIMAGER_SRL_ANNOTATOR_NAME}:${TEXTIMAGER_SRL_ANNOTATOR_VERSION} \
  -f src/main/docker/Dockerfile_cuda \
  .
