export TEXTIMAGER_BFSRL_ANNOTATOR_NAME=bfsrl
export TEXTIMAGER_BFSRL_ANNOTATOR_VERSION=0.1.0
export TEXTIMAGER_BFSRL_LOG_LEVEL=DEBUG
export TEXTIMAGER_BFSRL_PARSER_MODEL_NAME=de_hdt.dbmdz-bert-base

docker build \
  --build-arg TEXTIMAGER_BFSRL_ANNOTATOR_NAME \
  --build-arg TEXTIMAGER_BFSRL_ANNOTATOR_VERSION \
  --build-arg TEXTIMAGER_BFSRL_LOG_LEVEL \
  -t ${TEXTIMAGER_BFSRL_ANNOTATOR_NAME}:${TEXTIMAGER_BFSRL_ANNOTATOR_VERSION} \
  -f src/main/docker/Dockerfile \
  .
