
TEXTIMAGER_BFSRL_ANNOTATOR_NAME=bfsrl_cuda \
TEXTIMAGER_BFSRL_ANNOTATOR_VERSION=0.1.0 \
TEXTIMAGER_BFSRL_LOG_LEVEL=DEBUG \
TEXTIMAGER_BFSRL_PARSER_MODEL_NAME=de_hdt.dbmdz-bert-base \
TEXTIMAGER_SPACY_MODEL_CACHE_SIZE=3 \
TEXTIMAGER_DIAPARSER_BATCH_SIZE=8192 \
uvicorn textimager_duui_bfsrl:app --host 0.0.0.0 --port 8501 --workers 1
