#!/usr/bin/env bash
set -euo pipefail

export DUUI_SENTENCIZER_STANZA_ANNOTATOR_NAME=duui-sentencizer-stanza
export DUUI_SENTENCIZER_STANZA_ANNOTATOR_VERSION=0.0.1

#export DUUI_SENTENCIZER_STANZA_LOG_LEVEL=DEBUG
export DUUI_SENTENCIZER_STANZA_LOG_LEVEL=INFO

export DUUI_SENTENCIZER_STANZA_MODEL_CACHE_SIZE=2

export DOCKER_REGISTRY="docker.texttechnologylab.org/"

docker build \
  --build-arg DUUI_SENTENCIZER_STANZA_ANNOTATOR_NAME \
  --build-arg DUUI_SENTENCIZER_STANZA_ANNOTATOR_VERSION \
  --build-arg DUUI_SENTENCIZER_STANZA_LOG_LEVEL \
  --build-arg DUUI_SENTENCIZER_STANZA_MODEL_CACHE_SIZE \
  -t ${DOCKER_REGISTRY}${DUUI_SENTENCIZER_STANZA_ANNOTATOR_NAME}:${DUUI_SENTENCIZER_STANZA_ANNOTATOR_VERSION} \
  -f "src/main/docker/Dockerfile" \
  .

docker tag \
  ${DOCKER_REGISTRY}${DUUI_SENTENCIZER_STANZA_ANNOTATOR_NAME}:${DUUI_SENTENCIZER_STANZA_ANNOTATOR_VERSION} \
  ${DOCKER_REGISTRY}${DUUI_SENTENCIZER_STANZA_ANNOTATOR_NAME}:latest
