#!/usr/bin/env bash
set -euo pipefail

export COMPLEXITY_ANNOTATOR_CUDA=
#export COMPLEXITY_ANNOTATOR_CUDA="-cuda"

export COMPLEXITY_ANNOTATOR_NAME=duui-transformers-complexity
export COMPLEXITY_ANNOTATOR_VERSION=0.1.0
export COMPLEXITY_LOG_LEVEL=DEBUG
export COMPLEXITY_MODEL_CACHE_SIZE=3
export DOCKER_REGISTRY="docker.texttechnologylab.org/"


docker build \
  --build-arg COMPLEXITY_ANNOTATOR_NAME \
  --build-arg COMPLEXITY_ANNOTATOR_VERSION \
  --build-arg COMPLEXITY_LOG_LEVEL \
  -t ${DOCKER_REGISTRY}${COMPLEXITY_ANNOTATOR_NAME}:${COMPLEXITY_ANNOTATOR_VERSION}${COMPLEXITY_ANNOTATOR_CUDA} \
  -f src/main/docker/Dockerfile${COMPLEXITY_ANNOTATOR_CUDA} \
  .

docker tag \
  ${DOCKER_REGISTRY}${COMPLEXITY_ANNOTATOR_NAME}:${COMPLEXITY_ANNOTATOR_VERSION}${COMPLEXITY_ANNOTATOR_CUDA} \
  ${DOCKER_REGISTRY}${COMPLEXITY_ANNOTATOR_NAME}:latest${COMPLEXITY_ANNOTATOR_CUDA}
