#!/usr/bin/env bash
set -euo pipefail

export DUUI_PDF_EXTRACT_OCR_ANNOTATOR_NAME=duui-pdf-extract-ocr
export DUUI_PDF_EXTRACT_OCR_ANNOTATOR_VERSION=0.0.1

#export DUUI_PDF_EXTRACT_OCR_LOG_LEVEL=DEBUG
export DUUI_PDF_EXTRACT_OCR_LOG_LEVEL=INFO

export DOCKER_REGISTRY="docker.texttechnologylab.org/"

docker build \
  --build-arg DUUI_PDF_EXTRACT_OCR_ANNOTATOR_NAME \
  --build-arg DUUI_PDF_EXTRACT_OCR_ANNOTATOR_VERSION \
  --build-arg DUUI_PDF_EXTRACT_OCR_LOG_LEVEL \
  -t ${DOCKER_REGISTRY}${DUUI_PDF_EXTRACT_OCR_ANNOTATOR_NAME}:${DUUI_PDF_EXTRACT_OCR_ANNOTATOR_VERSION} \
  -f "src/main/docker/Dockerfile" \
  .

docker tag \
  ${DOCKER_REGISTRY}${DUUI_PDF_EXTRACT_OCR_ANNOTATOR_NAME}:${DUUI_PDF_EXTRACT_OCR_ANNOTATOR_VERSION} \
  ${DOCKER_REGISTRY}${DUUI_PDF_EXTRACT_OCR_ANNOTATOR_NAME}:latest
