FROM nvidia/cuda:12.4.0-base-ubuntu22.04

RUN apt update && \
    DEBIAN_FRONTEND=noninteractive \
    apt install --no-install-recommends -y build-essential software-properties-common && \
    add-apt-repository -y ppa:deadsnakes/ppa && \
    apt install --no-install-recommends -y python3.10 python3-pip python3-setuptools python3-distutils && \
    apt clean && rm -rf /var/lib/apt/lists/*

RUN ln -s /usr/bin/python3 /usr/bin/python
RUN python -m pip install --upgrade pip

WORKDIR /usr/src/app

EXPOSE 9714


# copy scripts
COPY ./src/main/python/config.yaml ./config.yaml
COPY ./src/main/python/TypeSystemBertTopic.xml ./TypeSystemUnifiedTopic.xml
COPY ./src/main/python/duui-transformers-berttopic.py ./duui-transformers-berttopic.py
COPY ./src/main/python/duui-transformers-berttopic.lua ./duui-transformers-berttopic.lua



# dependencies
# Fix for blinker 1.4 error, source: https://github.com/googlecolab/colabtools/issues/3976
RUN apt-get remove python3-blinker -y
RUN pip install blinker==1.6.2

RUN pip install torch==2.5.0 torchvision==0.20.0 torchaudio==2.5.0 --index-url https://download.pytorch.org/whl/cu118
COPY ./requirements.txt ./requirements.txt
RUN pip install -r requirements.txt



ENTRYPOINT ["uvicorn", "duui-transformers-berttopic:app", "--host", "0.0.0.0", "--port" ,"9714"]
CMD ["--workers", "1"]
