FROM nvidia/cuda:11.8.0-base-ubuntu22.04

RUN apt update && \
    DEBIAN_FRONTEND=noninteractive \
    apt install --no-install-recommends -y build-essential software-properties-common && \
    add-apt-repository -y ppa:deadsnakes/ppa && \
    apt install --no-install-recommends -y python3.10 python3-pip python3-setuptools python3-distutils && \
    apt clean && rm -rf /var/lib/apt/lists/*

RUN ln -s /usr/bin/python3 /usr/bin/python
RUN python -m pip install --upgrade pip

WORKDIR /usr/src/app

EXPOSE 9714


# copy scripts
COPY ./src/main/python/config.yaml ./config.yaml
COPY ./src/main/python/TypeSystemBertTopic.xml ./TypeSystemBertTopic.xml
COPY ./src/main/python/duui_transformers_berttopic.py ./duui_transformers_berttopic.py
COPY ./src/main/python/duui_transformers_berttopic.lua ./duui_transformers_berttopic.lua


# dependencies
RUN pip install torch==2.3.0 torchvision==0.18.0 torchaudio==2.3.0 --index-url https://download.pytorch.org/whl/cu118
COPY ./requirements.txt ./requirements.txt
RUN pip install -r requirements.txt



ENTRYPOINT ["uvicorn", "duui_transformers_berttopic:app", "--host", "0.0.0.0", "--port" ,"9714"]
CMD ["--workers", "1"]
