export TEXTIMAGER_SPACY_SINGLE_MODEL_LANG=de
export TEXTIMAGER_SPACY_SINGLE_MODEL=de_core_news_sm
export TEXTIMAGER_SPACY_ANNOTATOR_NAME=textimager-duui-spacy-single-$TEXTIMAGER_SPACY_SINGLE_MODEL
export TEXTIMAGER_SPACY_ANNOTATOR_VERSION=0.1.6
export TEXTIMAGER_SPACY_LOG_LEVEL=DEBUG
export TEXTIMAGER_SPACY_MODEL_CACHE_SIZE=3

export DOCKER_REGISTRY="docker.texttechnologylab.org/"

docker build \
  --build-arg TEXTIMAGER_SPACY_ANNOTATOR_NAME \
  --build-arg TEXTIMAGER_SPACY_ANNOTATOR_VERSION \
  --build-arg TEXTIMAGER_SPACY_LOG_LEVEL \
  --build-arg TEXTIMAGER_SPACY_SINGLE_MODEL_LANG \
  --build-arg TEXTIMAGER_SPACY_SINGLE_MODEL \
  -t ${DOCKER_REGISTRY}${TEXTIMAGER_SPACY_ANNOTATOR_NAME}:${TEXTIMAGER_SPACY_ANNOTATOR_VERSION} \
  -f src/main/docker/Dockerfile_single_model \
  .

docker tag \
  ${DOCKER_REGISTRY}${TEXTIMAGER_SPACY_ANNOTATOR_NAME}:${TEXTIMAGER_SPACY_ANNOTATOR_VERSION} \
  ${DOCKER_REGISTRY}${TEXTIMAGER_SPACY_ANNOTATOR_NAME}:latest
