#!/usr/bin/env bash
set -euo pipefail

export IMAGE_TO_TEXT_ANNOTATOR_CUDA=
#export EMOTION_ANNOTATOR_CUDA="-cuda"

export IMAGE_TO_TEXT_ANNOTATOR_NAME=duui-text-to-image
export IMAGE_TO_TEXT_ANNOTATOR_VERSION=0.2.0
export IMAGE_TO_TEXT_LOG_LEVEL=DEBUG
export IMAGE_TO_TEXT_MODEL_CACHE_SIZE=3
export DOCKER_REGISTRY="docker.texttechnologylab.org/"
export IMAGE_TO_TEXT_HUGGING_FACE_TOKEN="unset"


docker build \
  --build-arg IMAGE_TO_TEXT_ANNOTATOR_NAME \
  --build-arg IMAGE_TO_TEXT_ANNOTATOR_VERSION \
  --build-arg IMAGE_TO_TEXT_LOG_LEVEL \
  -t ${DOCKER_REGISTRY}${IMAGE_TO_TEXT_ANNOTATOR_NAME}:${IMAGE_TO_TEXT_ANNOTATOR_VERSION}${IMAGE_TO_TEXT_ANNOTATOR_CUDA} \
  -f src/main/docker/Dockerfile${IMAGE_TO_TEXT_ANNOTATOR_CUDA} \
  .

docker tag \
  ${DOCKER_REGISTRY}${IMAGE_TO_TEXT_ANNOTATOR_NAME}:${IMAGE_TO_TEXT_ANNOTATOR_VERSION}${IMAGE_TO_TEXT_ANNOTATOR_CUDA} \
  ${DOCKER_REGISTRY}${IMAGE_TO_TEXT_ANNOTATOR_NAME}:latest${IMAGE_TO_TEXT_ANNOTATOR_CUDA}

