#!/usr/bin/env bash
set -euo pipefail

export DUUI_CRISPER_WHISPER_ANNOTATOR_NAME=duui-crisper-whisper
export DUUI_CRISPER_WHISPER_ANNOTATOR_VERSION=0.0.1

export DUUI_CRISPER_WHISPER_VARIANT=
#export DUUI_CRISPER_WHISPER_VARIANT=-cuda

export DUUI_CRISPER_WHISPER_LOG_LEVEL=DEBUG
#export DUUI_CRISPER_WHISPER_LOG_LEVEL=INFO

export DOCKER_REGISTRY="docker.texttechnologylab.org/"

docker build \
  --build-arg DUUI_CRISPER_WHISPER_ANNOTATOR_NAME \
  --build-arg DUUI_CRISPER_WHISPER_ANNOTATOR_VERSION \
  --build-arg DUUI_CRISPER_WHISPER_LOG_LEVEL \
  -t ${DOCKER_REGISTRY}${DUUI_CRISPER_WHISPER_ANNOTATOR_NAME}:${DUUI_CRISPER_WHISPER_ANNOTATOR_VERSION}${DUUI_CRISPER_WHISPER_VARIANT} \
  -f "src/main/docker/Dockerfile${DUUI_CRISPER_WHISPER_VARIANT}" \
  --progress=plain \
  .

docker tag \
  ${DOCKER_REGISTRY}${DUUI_CRISPER_WHISPER_ANNOTATOR_NAME}:${DUUI_CRISPER_WHISPER_ANNOTATOR_VERSION}${DUUI_CRISPER_WHISPER_VARIANT} \
  ${DOCKER_REGISTRY}${DUUI_CRISPER_WHISPER_ANNOTATOR_NAME}:latest${DUUI_CRISPER_WHISPER_VARIANT}
