#!/usr/bin/env bash
set -euo pipefail

export DUUI_SENTENCE_TRANSFORMERS_ANNOTATOR_NAME=duui-sentence-transformers
export DUUI_SENTENCE_TRANSFORMERS_ANNOTATOR_VERSION=0.0.1

#export DUUI_SENTENCE_TRANSFORMERS_LOG_LEVEL=DEBUG
export DUUI_SENTENCE_TRANSFORMERS_LOG_LEVEL=INFO

export DUUI_SENTENCE_TRANSFORMERS_MODEL_CACHE_SIZE=1

export DOCKER_REGISTRY="docker.texttechnologylab.org/"

docker build \
  --build-arg DUUI_SENTENCE_TRANSFORMERS_ANNOTATOR_NAME \
  --build-arg DUUI_SENTENCE_TRANSFORMERS_ANNOTATOR_VERSION \
  --build-arg DUUI_SENTENCE_TRANSFORMERS_LOG_LEVEL \
  -t ${DOCKER_REGISTRY}${DUUI_SENTENCE_TRANSFORMERS_ANNOTATOR_NAME}:${DUUI_SENTENCE_TRANSFORMERS_ANNOTATOR_VERSION} \
  -f "src/main/docker/Dockerfile" \
  .

docker tag \
  ${DOCKER_REGISTRY}${DUUI_SENTENCE_TRANSFORMERS_ANNOTATOR_NAME}:${DUUI_SENTENCE_TRANSFORMERS_ANNOTATOR_VERSION} \
  ${DOCKER_REGISTRY}${DUUI_SENTENCE_TRANSFORMERS_ANNOTATOR_NAME}:latest
