#!/usr/bin/env bash
set -euo pipefail

export TOPIC_ANNOTATOR_CUDA=
#export TOPIC_ANNOTATOR_CUDA="-cuda"

export TOPIC_ANNOTATOR_NAME=duui-transformers-topic
export TOPIC_ANNOTATOR_VERSION=0.2.0
export TOPIC_LOG_LEVEL=DEBUG
export TOPIC_MODEL_CACHE_SIZE=3
export DOCKER_REGISTRY="docker.texttechnologylab.org/"


docker build \
  --build-arg TOPIC_ANNOTATOR_NAME \
  --build-arg TOPIC_ANNOTATOR_VERSION \
  --build-arg TOPIC_LOG_LEVEL \
  -t ${DOCKER_REGISTRY}${TOPIC_ANNOTATOR_NAME}:${TOPIC_ANNOTATOR_VERSION}${TOPIC_ANNOTATOR_CUDA} \
  -f src/main/docker/Dockerfile${TOPIC_ANNOTATOR_CUDA} \
  .

docker tag \
  ${DOCKER_REGISTRY}${TOPIC_ANNOTATOR_NAME}:${TOPIC_ANNOTATOR_VERSION}${TOPIC_ANNOTATOR_CUDA} \
  ${DOCKER_REGISTRY}${TOPIC_ANNOTATOR_NAME}:latest${TOPIC_ANNOTATOR_CUDA}
