FROM docker.texttechnologylab.org/duui-face-anon-simple:latest

USER root

RUN apt-get update \
    && apt-get install -y --no-install-recommends \
        libgl1 \
        libglib2.0-0 \
    && rm -rf /var/lib/apt/lists/*