export TEXTIMAGER_UDEPPARSER_ANNOTATOR_NAME=udpparser
export TEXTIMAGER_UDEPPARSER_ANNOTATOR_VERSION=0.0.1
export TEXTIMAGER_UDEPPARSER_LOG_LEVEL=INFO
export TEXTIMAGER_UDEPPARSER_PARSER_MODEL_NAME=de_hdt.dbmdz-bert-base

docker build \
  --build-arg TEXTIMAGER_UDEPPARSER_ANNOTATOR_NAME \
  --build-arg TEXTIMAGER_UDEPPARSER_ANNOTATOR_VERSION \
  --build-arg TEXTIMAGER_UDEPPARSER_LOG_LEVEL \
  -t ${TEXTIMAGER_UDEPPARSER_ANNOTATOR_NAME}:${TEXTIMAGER_UDEPPARSER_ANNOTATOR_VERSION} \
  -f src/main/docker/Dockerfile \
  .
