#!/usr/bin/env bash
set -euo pipefail

export ARGUMWNT_ANNOTATOR_CUDA=
#export ARGUMWNT_ANNOTATOR_CUDA="-cuda"

export ARGUMWNT_ANNOTATOR_NAME=duui-argument
export ARGUMWNT_ANNOTATOR_VERSION=0.0.1
export ARGUMWNT_LOG_LEVEL=DEBUG
export ARGUMWNT_MODEL_CACHE_SIZE=3
export CHATGPT_KEY=
export DOCKER_REGISTRY="docker.texttechnologylab.org/"


docker build \
  --build-arg ARGUMWNT_ANNOTATOR_NAME \
  --build-arg ARGUMWNT_ANNOTATOR_VERSION \
  --build-arg ARGUMWNT_LOG_LEVEL \
  -t ${DOCKER_REGISTRY}${ARGUMWNT_ANNOTATOR_NAME}:${ARGUMWNT_ANNOTATOR_VERSION}${ARGUMWNT_ANNOTATOR_CUDA} \
  -f src/main/docker/Dockerfile${ARGUMWNT_ANNOTATOR_CUDA} \
  .

docker tag \
  ${DOCKER_REGISTRY}${ARGUMWNT_ANNOTATOR_NAME}:${ARGUMWNT_ANNOTATOR_VERSION}${ARGUMWNT_ANNOTATOR_CUDA} \
  ${DOCKER_REGISTRY}${ARGUMWNT_ANNOTATOR_NAME}:latest${ARGUMWNT_ANNOTATOR_CUDA}
