export TEXTIMAGER_DIAPARSER_BATCH_SIZE=$1
export TEXTIMAGER_BFSRL_ANNOTATOR_NAME=bfsrl_cuda_$TEXTIMAGER_DIAPARSER_BATCH_SIZE
export TEXTIMAGER_BFSRL_ANNOTATOR_VERSION=0.2.1
export TEXTIMAGER_BFSRL_LOG_LEVEL=DEBUG
export TEXTIMAGER_BFSRL_PARSER_MODEL_NAME=de_hdt.dbmdz-bert-base

docker build \
  --build-arg TEXTIMAGER_BFSRL_ANNOTATOR_NAME \
  --build-arg TEXTIMAGER_BFSRL_ANNOTATOR_VERSION \
  --build-arg TEXTIMAGER_BFSRL_LOG_LEVEL \
  --build-arg TEXTIMAGER_DIAPARSER_BATCH_SIZE \
  -t ${TEXTIMAGER_BFSRL_ANNOTATOR_NAME}:${TEXTIMAGER_BFSRL_ANNOTATOR_VERSION} \
  -f src/main/docker/Dockerfile_cuda \
  .
