
TEXTIMAGER_UDEPPARSER_ANNOTATOR_NAME=udep_cuda \
TEXTIMAGER_UDEPPARSER_ANNOTATOR_VERSION=0.0.1 \
TEXTIMAGER_UDEPPARSER_LOG_LEVEL=INFO \
TEXTIMAGER_UDEPPARSER_MODEL_NAME=de_hdt.dbmdz-bert-base \
TEXTIMAGER_UDEPPARSER_BATCH_SIZE=1024 \
uvicorn textimager_duui_udep:app --host 0.0.0.0 --port 8501 --workers 1
